/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_lab_josuezelaya;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class Ventana_Examen2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Examen2
     */
    public Ventana_Examen2() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);//cuandro abrimos sale maximizada
        Abrir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crear_usuario = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nombre_usuario = new javax.swing.JTextField();
        sp_edad_usuario = new javax.swing.JSpinner();
        tf_username_usuario = new javax.swing.JTextField();
        ps_password_usuario = new javax.swing.JPasswordField();
        boton_guardar_usuario = new javax.swing.JButton();
        jd_crear_canciones = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_duracion_cancion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_nombre_cancion = new javax.swing.JTextField();
        tf_artista_cancion = new javax.swing.JTextField();
        tf_genero_cancion = new javax.swing.JTextField();
        boton_guardar_cancion = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cb_album_cancion = new javax.swing.JComboBox<>();
        jd_listar_usuarios = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        menu_popup = new javax.swing.JPopupMenu();
        menu_eliminar_usuarios = new javax.swing.JMenuItem();
        jd_crear_album = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_nombre_album = new javax.swing.JTextField();
        tf_artista_album = new javax.swing.JTextField();
        boton_guardar_album = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_usuarios = new javax.swing.JMenu();
        menu_crear_usuario = new javax.swing.JMenuItem();
        listar_usuario = new javax.swing.JMenuItem();
        menu_crear_canciones = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_crear_album = new javax.swing.JMenuItem();
        menu_listar_album = new javax.swing.JMenuItem();
        menu_eliminar_album = new javax.swing.JMenuItem();
        menu_cargar_usuario = new javax.swing.JMenuItem();
        menu_guardar_usuarios = new javax.swing.JMenuItem();

        jLabel1.setText("Crear Usuario");

        jLabel2.setText("Nombre");

        jLabel3.setText("Edad");

        jLabel4.setText("Username");

        jLabel5.setText("Password");

        boton_guardar_usuario.setText("Guardar");
        boton_guardar_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_guardar_usuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crear_usuarioLayout = new javax.swing.GroupLayout(jd_crear_usuario.getContentPane());
        jd_crear_usuario.getContentPane().setLayout(jd_crear_usuarioLayout);
        jd_crear_usuarioLayout.setHorizontalGroup(
            jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_edad_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tf_username_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ps_password_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(boton_guardar_usuario)
                .addGap(50, 50, 50))
        );
        jd_crear_usuarioLayout.setVerticalGroup(
            jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sp_edad_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_username_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(ps_password_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(boton_guardar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jd_crear_canciones.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jd_crear_cancionesWindowActivated(evt);
            }
        });

        jLabel6.setText("Crear Canciones");

        jLabel7.setText("Nombre");

        jLabel8.setText("Artista");

        jLabel9.setText("Duracion");

        jLabel10.setText("Genero");

        boton_guardar_cancion.setText("Guardar");
        boton_guardar_cancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_guardar_cancionMouseClicked(evt);
            }
        });

        jLabel16.setText("Album");

        javax.swing.GroupLayout jd_crear_cancionesLayout = new javax.swing.GroupLayout(jd_crear_canciones.getContentPane());
        jd_crear_canciones.getContentPane().setLayout(jd_crear_cancionesLayout);
        jd_crear_cancionesLayout.setHorizontalGroup(
            jd_crear_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_cancionesLayout.createSequentialGroup()
                .addGroup(jd_crear_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crear_cancionesLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel6))
                    .addGroup(jd_crear_cancionesLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jd_crear_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(boton_guardar_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_crear_cancionesLayout.createSequentialGroup()
                                .addGroup(jd_crear_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel16))
                                .addGap(41, 41, 41)
                                .addGroup(jd_crear_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_duracion_cancion)
                                    .addComponent(tf_nombre_cancion)
                                    .addComponent(tf_artista_cancion)
                                    .addComponent(tf_genero_cancion)
                                    .addComponent(cb_album_cancion, 0, 214, Short.MAX_VALUE))))))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jd_crear_cancionesLayout.setVerticalGroup(
            jd_crear_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_cancionesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addGroup(jd_crear_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_nombre_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jd_crear_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_artista_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jd_crear_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(tf_duracion_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_crear_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_genero_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jd_crear_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cb_album_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(boton_guardar_cancion)
                .addGap(63, 63, 63))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Usuarios");

        tabla1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabla1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla1);

        jLabel12.setText("Click derecho para eliminar");

        javax.swing.GroupLayout jd_listar_usuariosLayout = new javax.swing.GroupLayout(jd_listar_usuarios.getContentPane());
        jd_listar_usuarios.getContentPane().setLayout(jd_listar_usuariosLayout);
        jd_listar_usuariosLayout.setHorizontalGroup(
            jd_listar_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listar_usuariosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listar_usuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(297, 297, 297))
        );
        jd_listar_usuariosLayout.setVerticalGroup(
            jd_listar_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listar_usuariosLayout.createSequentialGroup()
                .addGroup(jd_listar_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_listar_usuariosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel11)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_listar_usuariosLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel12)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        menu_eliminar_usuarios.setText("Eliminar");
        menu_eliminar_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_eliminar_usuariosActionPerformed(evt);
            }
        });
        menu_popup.add(menu_eliminar_usuarios);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Crear Albums");

        jLabel14.setText("Nombre");

        jLabel15.setText("Artista");

        boton_guardar_album.setText("Guardar");
        boton_guardar_album.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_guardar_albumMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crear_albumLayout = new javax.swing.GroupLayout(jd_crear_album.getContentPane());
        jd_crear_album.getContentPane().setLayout(jd_crear_albumLayout);
        jd_crear_albumLayout.setHorizontalGroup(
            jd_crear_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crear_albumLayout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(129, 129, 129))
            .addGroup(jd_crear_albumLayout.createSequentialGroup()
                .addGroup(jd_crear_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crear_albumLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jd_crear_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(37, 37, 37)
                        .addGroup(jd_crear_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombre_album, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(tf_artista_album)))
                    .addGroup(jd_crear_albumLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(boton_guardar_album)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_crear_albumLayout.setVerticalGroup(
            jd_crear_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_albumLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addGap(56, 56, 56)
                .addGroup(jd_crear_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_nombre_album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jd_crear_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_artista_album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(boton_guardar_album)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Opciones");

        menu_usuarios.setText("Usuarios");

        menu_crear_usuario.setText("Crear");
        menu_crear_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_crear_usuarioActionPerformed(evt);
            }
        });
        menu_usuarios.add(menu_crear_usuario);

        listar_usuario.setText("Listar, Eliminar");
        listar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listar_usuarioActionPerformed(evt);
            }
        });
        menu_usuarios.add(listar_usuario);

        jMenu1.add(menu_usuarios);

        menu_crear_canciones.setText("Crear Canciones");
        menu_crear_canciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_crear_cancionesActionPerformed(evt);
            }
        });
        jMenu1.add(menu_crear_canciones);

        jMenu2.setText("Albums");

        menu_crear_album.setText("Crear");
        menu_crear_album.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_crear_albumActionPerformed(evt);
            }
        });
        jMenu2.add(menu_crear_album);

        menu_listar_album.setText("Listar");
        jMenu2.add(menu_listar_album);

        menu_eliminar_album.setText("Eliminar");
        jMenu2.add(menu_eliminar_album);

        jMenu1.add(jMenu2);

        menu_cargar_usuario.setText("Cargar Usuarios");
        menu_cargar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cargar_usuarioActionPerformed(evt);
            }
        });
        jMenu1.add(menu_cargar_usuario);

        menu_guardar_usuarios.setText("Guardar Usuarios");
        menu_guardar_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_guardar_usuariosActionPerformed(evt);
            }
        });
        jMenu1.add(menu_guardar_usuarios);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listar_usuarioActionPerformed

        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Nombre");
        modelo.addColumn("Edad");
        modelo.addColumn("Username");
        for (Usuario temp : usuarios) {

            Object[] newrow = {
                temp.getNombre(),
                temp.getEdad(),
                temp.getUsername(),};
            modelo.addRow(newrow);

            tabla1.setModel(modelo);

        }
        jd_listar_usuarios.setModal(true);
        jd_listar_usuarios.pack();
        jd_listar_usuarios.setLocationRelativeTo(this);
        jd_listar_usuarios.setVisible(true);

    }//GEN-LAST:event_listar_usuarioActionPerformed

    private void menu_crear_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_crear_usuarioActionPerformed
        jd_crear_usuario.setModal(true);
        jd_crear_usuario.pack();
        jd_crear_usuario.setLocationRelativeTo(this);
        jd_crear_usuario.setVisible(true);
    }//GEN-LAST:event_menu_crear_usuarioActionPerformed

    private void boton_guardar_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_guardar_usuarioMouseClicked
        try {
            String nombre = tf_nombre_usuario.getText();
            int edad = Integer.parseInt(sp_edad_usuario.getValue().toString());
            String username = tf_username_usuario.getText();
            String password = ps_password_usuario.getText();
            us = (new Usuario(nombre, edad, username, password));
            usuarios.add(new Usuario(nombre, edad, username, password));

            
            JOptionPane.showMessageDialog(this, "Se agrego exitosamente");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_boton_guardar_usuarioMouseClicked

    private void menu_crear_cancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_crear_cancionesActionPerformed
        jd_crear_canciones.setModal(true);
        jd_crear_canciones.pack();
        jd_crear_canciones.setLocationRelativeTo(this);
        jd_crear_canciones.setVisible(true);
    }//GEN-LAST:event_menu_crear_cancionesActionPerformed

    private void boton_guardar_cancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_guardar_cancionMouseClicked
        if (album.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se ha creado un album");
        } else {
            System.out.println("entro");
            try {
                String nombre = tf_nombre_cancion.getText();
                String artista = tf_artista_cancion.getText();
                int duracion = Integer.parseInt(tf_duracion_cancion.getText());
                String genero = tf_genero_cancion.getText();
                canciones.add(new Canciones(nombre, artista, duracion, genero));
                JOptionPane.showMessageDialog(this, "Se agrego exitosamente");
                
                String nombre_album=cb_album_cancion.getSelectedItem().toString();
                for (Album temp : album) {
                    if (nombre_album.equals(temp.getNombre())){
                        temp.setCanciones_agregadas(canciones);
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_boton_guardar_cancionMouseClicked

    private void tabla1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla1MouseReleased


    }//GEN-LAST:event_tabla1MouseReleased

    private void menu_eliminar_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_eliminar_usuariosActionPerformed
        int row = tabla1.getSelectedRow();
        usuarios.remove(row);
        DefaultTableModel dtm = (DefaultTableModel) tabla1.getModel();
        dtm.removeRow(row);
    }//GEN-LAST:event_menu_eliminar_usuariosActionPerformed

    private void tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla1MouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            menu_popup.show(tabla1.getComponentAt(tabla1.getX(), tabla1.getY()), tabla1.getX(), tabla1.getY());
        } else {

            menu_popup.show(tabla1.getComponentAt(tabla1.getX(), tabla1.getY()), tabla1.getX(), tabla1.getY());
        }
    }//GEN-LAST:event_tabla1MouseClicked

    private void menu_cargar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cargar_usuarioActionPerformed

    }//GEN-LAST:event_menu_cargar_usuarioActionPerformed

    private void menu_guardar_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_guardar_usuariosActionPerformed
        au = new adminUsuario("./usuario.cbm");
        au.CargarArchivo();
        au.setUsuario(us);
        au.EscribirArchivo();
        //para que no me suscriba los usuarios
            Guardar(usuarios);
    }//GEN-LAST:event_menu_guardar_usuariosActionPerformed

    private void menu_crear_albumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_crear_albumActionPerformed
        
        jd_crear_album.setModal(true);
        jd_crear_album.pack();
        jd_crear_album.setLocationRelativeTo(this);
        jd_crear_album.setVisible(true);
    }//GEN-LAST:event_menu_crear_albumActionPerformed

    private void boton_guardar_albumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_guardar_albumMouseClicked
        try {
            String nombre=tf_nombre_album.getText();
        String artista=tf_artista_album.getText();
        album.add(new Album(nombre, artista));
        JOptionPane.showMessageDialog(this, "Se agrego exitosamente");
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_boton_guardar_albumMouseClicked

    private void jd_crear_cancionesWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_crear_cancionesWindowActivated
        // TODO add your handling code here:
        if (jd_crear_canciones.isActive()){
            DefaultComboBoxModel modelo
                    = new DefaultComboBoxModel();
            for (Album temp : album) {
                modelo.addElement(temp);
             
            }
            cb_album_cancion.setModel(modelo);
        }
    }//GEN-LAST:event_jd_crear_cancionesWindowActivated

    public void Guardar(ArrayList usuarios) {
        try {
            FileOutputStream archivo = new FileOutputStream("./usuario.cbm");
            ObjectOutputStream os = new ObjectOutputStream(archivo);
            os.writeObject(usuarios);
            os.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void Abrir() {
        try {
            FileInputStream entrada = new FileInputStream("./usuario.cbm");
            ObjectInputStream oi = new ObjectInputStream(entrada);
            try {
                usuarios = (ArrayList<Usuario>) oi.readObject();
            } catch (ClassNotFoundException e) {

            }
        } catch (IOException e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Examen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Examen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Examen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Examen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Examen2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_guardar_album;
    private javax.swing.JButton boton_guardar_cancion;
    private javax.swing.JButton boton_guardar_usuario;
    private javax.swing.JComboBox<String> cb_album_cancion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd_crear_album;
    private javax.swing.JDialog jd_crear_canciones;
    private javax.swing.JDialog jd_crear_usuario;
    private javax.swing.JDialog jd_listar_usuarios;
    private javax.swing.JMenuItem listar_usuario;
    private javax.swing.JMenuItem menu_cargar_usuario;
    private javax.swing.JMenuItem menu_crear_album;
    private javax.swing.JMenuItem menu_crear_canciones;
    private javax.swing.JMenuItem menu_crear_usuario;
    private javax.swing.JMenuItem menu_eliminar_album;
    private javax.swing.JMenuItem menu_eliminar_usuarios;
    private javax.swing.JMenuItem menu_guardar_usuarios;
    private javax.swing.JMenuItem menu_listar_album;
    private javax.swing.JPopupMenu menu_popup;
    private javax.swing.JMenu menu_usuarios;
    private javax.swing.JPasswordField ps_password_usuario;
    private javax.swing.JSpinner sp_edad_usuario;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField tf_artista_album;
    private javax.swing.JTextField tf_artista_cancion;
    private javax.swing.JTextField tf_duracion_cancion;
    private javax.swing.JTextField tf_genero_cancion;
    private javax.swing.JTextField tf_nombre_album;
    private javax.swing.JTextField tf_nombre_cancion;
    private javax.swing.JTextField tf_nombre_usuario;
    private javax.swing.JTextField tf_username_usuario;
    // End of variables declaration//GEN-END:variables
ArrayList<Usuario> usuarios = new ArrayList();
    adminUsuario au;
    Usuario us = new Usuario();
    ArrayList<Canciones> canciones = new ArrayList();
    ArrayList<Album> album = new ArrayList();
}
